// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ossrjrjebgdkgdjuhdhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zc3JqcmplYmdka2dkanVoZGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODIwMTUsImV4cCI6MjA2MzA1ODAxNX0.gA4k_D71k14i4BRyxQ5gObaK1Ngss6kYBye8Mc6-WwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);